/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grego.vgrep.gui;

import com.grego.vgrep.gui.model.PreviewTableModel;
import java.util.Collection;
import javax.swing.JOptionPane;

/**
 *
 * @author Grigorios
 */
public class PrepareReferencesUI extends javax.swing.JFrame {

    private void resizeDivider() {
        this.jSplitPaneTables.setDividerLocation(0.5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jButtonFinish = new javax.swing.JButton();
        jSplitPaneTables = new javax.swing.JSplitPane();
        jScrollPaneTarget = new javax.swing.JScrollPane();
        jTableTarget = new javax.swing.JTable();
        jScrollPaneInfo = new javax.swing.JScrollPane();
        jTableInfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("File Preview");

        jButtonFinish.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonFinish.setText("Finish");
        jButtonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFinish)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jButtonFinish)
                .addContainerGap())
        );

        jSplitPaneTables.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Reference Selection", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 36), new java.awt.Color(0, 0, 0))); // NOI18N
        jSplitPaneTables.setDividerLocation(360);

        jScrollPaneTarget.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Target File", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 24))); // NOI18N

        jTableTarget.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableTarget.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableTarget.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableTarget.setColumnSelectionAllowed(true);
        jTableTarget.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableTarget.setRowHeight(23);
        jTableTarget.setRowSelectionAllowed(false);
        jScrollPaneTarget.setViewportView(jTableTarget);

        jSplitPaneTables.setRightComponent(jScrollPaneTarget);

        jScrollPaneInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info File", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 0, 24))); // NOI18N

        jTableInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableInfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableInfo.setColumnSelectionAllowed(true);
        jTableInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableInfo.setRowHeight(23);
        jTableInfo.setRowSelectionAllowed(false);
        jTableInfo.getTableHeader().setReorderingAllowed(false);
        jScrollPaneInfo.setViewportView(jTableInfo);
        jTableInfo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jSplitPaneTables.setLeftComponent(jScrollPaneInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSplitPaneTables, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPaneTables, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinishActionPerformed
        int[] infoSelectedCols = jTableInfo.getSelectedColumns();
        int[] targetSelectedCols = jTableTarget.getSelectedColumns();

        Collection<String> infoCollection = ((PreviewTableModel) jTableInfo.getModel()).getDataFromColumns(infoSelectedCols);
        Collection<String> targetCollection = ((PreviewTableModel) jTableTarget.getModel()).getDataFromColumns(targetSelectedCols);

        if (infoCollection.isEmpty() && targetCollection.isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Please select columns from both file preview\nto proceed!!",
                    "Reference Selection Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonFinishActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonFinish;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPaneInfo;
    private javax.swing.JScrollPane jScrollPaneTarget;
    private javax.swing.JSplitPane jSplitPaneTables;
    private javax.swing.JTable jTableInfo;
    private javax.swing.JTable jTableTarget;
    // End of variables declaration//GEN-END:variables
}
